import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div className={styles.container_backdrop}>
      <div className={styles.container_foreground}>
      <Head>
        <title>Angel P</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav_bar}>
        <div className={styles.nav_left}>
          Hello
        </div> 
        <div className={styles.nav_right}>
          <div>Hello</div>
          <div>But</div>
          <div>With</div>
          <div>Divisions</div>
        </div>
      </div>
      <div className={styles.main_page}>
          <Hero/>
          <div className={styles.projects_header}>Projects</div>

      </div>
      </div>
    </div>
  )
}
